---
title: Ahad's dev log
description: Ahad L. Amdani's personal development blog covering software engineering insights, technical deep dives, and project experiences.
url: https://ahad.dev
timezone: America/Chicago
collections:
  entries:
    title: Entries
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty

# SEO and sitemap
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
